# Generated by Django 6.0.4 on 2026-04-20 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='completed',
            new_name='is_done',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='duration_min',
        ),
        migrations.AddField(
            model_name='workout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
