# Generated by Django 6.0.4 on 2026-04-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_rename_completed_workout_is_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='duration_min',
            field=models.IntegerField(default=30),
        ),
    ]
